### ISSUE TITLE
DependencyClone is private

### ISSUE THREAD

**Issue by ahouts** [p0lunin/teloc#6]
The documentation for `ServiceProvider.add_instance` mentions you should implement `dependency::DependencyClone` for types that can be cloned, but the trait is in the module `dependency` which is private. 
Making the module public or re-exporting the trait in a public module would resolve this.

**Comment by p0lunin** [comment]
Thanks for the report! I'll fix this as soon as I can.

**Comment by dzmitry-lahoda** [comment]
hm, is it possible to Arc/Rc/Arc<Mutex>/&'container share dependencies? Or sharing is always cloning?

**Comment by p0lunin** [comment]
@dzmitry-lahoda you can share both by reference and cloning. For more information you can see https://docs.rs/teloc/0.1.0/teloc/struct.ServiceProvider.html#method.add_singleton.
